module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#474d4d",
        "tertiary-container": "#5f6564",
        "rust-600": "#B14A3A",
        "on-error": "#ffffff",
        "on-primary-container": "#adeede",
        "amber-500": "#C98A2C",
        "secondary-container": "#d2e2ed",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e3e1",
        "on-secondary-container": "#55656e",
        "on-primary-fixed": "#00201b",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeec",
        "primary-fixed": "#afefe0",
        "ink-900": "#1C2B33",
        "outline-variant": "#bfc9c5",
        "on-secondary-fixed": "#0e1d25",
        "on-error-container": "#93000a",
        "on-surface": "#191c1b",
        "paper-50": "#F7F8F6",
        "secondary-fixed": "#d5e5f0",
        "on-background": "#191c1b",
        "tertiary-fixed": "#dee3e2",
        "moss-500": "#5C8A5A",
        "surface": "#f9faf8",
        "secondary": "#51616a",
        "surface-bright": "#f9faf8",
        "on-surface-variant": "#3f4946",
        "primary-container": "#2e6e62",
        "primary": "#0e554a",
        "outline": "#6f7976",
        "surface-container-highest": "#e2e3e1",
        "on-tertiary-fixed-variant": "#424847",
        "on-tertiary": "#ffffff",
        "background": "#f9faf8",
        "surface-container-low": "#f3f4f2",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1ef",
        "surface-dim": "#d9dad8",
        "on-tertiary-container": "#dde2e1",
        "teal-600": "#2E6E62",
        "surface-container-high": "#e7e8e6",
        "on-primary-fixed-variant": "#045045",
        "primary-fixed-dim": "#93d3c4",
        "inverse-primary": "#93d3c4",
        "slate-200": "#DCE1E0",
        "tertiary-fixed-dim": "#c2c7c7",
        "on-tertiary-fixed": "#171d1c",
        "surface-tint": "#28695d",
        "on-secondary-fixed-variant": "#3a4951",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b9c9d3",
        "inverse-surface": "#2e3130"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "unit": "4px",
        "margin-mobile": "16px",
        "sm": "8px",
        "gutter": "16px",
        "margin-desktop": "40px",
        "xl": "32px",
        "lg": "24px",
        "xs": "4px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Fraunces", "serif"],
        "headline-md": ["Fraunces", "serif"],
        "display-lg-mobile": ["Fraunces", "serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["IBM Plex Mono", "monospace"],
        "display-lg": ["Fraunces", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-mono-sm": ["IBM Plex Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "display-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["11px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "data-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "450" }],
        "display-lg": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "data-mono-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "450" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
